package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class UserLoginController {
	
	@FXML
	public Button quitButton;
	
	@FXML
	public Label myLabel;
	
	@FXML
	public ComboBox userList;
	
	@FXML
	public Button loginExistingUser;
	
	@FXML
	public Button createNewUser;
	
	@FXML
	public TextField passwordInput;
	
	@FXML
	public Button loginConfirm;

	@FXML
	public Button goBack;
	
	@FXML
	public void goBackPress(ActionEvent event) throws IOException {
		StorageAndSetUps.getInstance().ulc.passwordInput.setVisible(false);
		StorageAndSetUps.getInstance().ulc.userList.setVisible(false);
		StorageAndSetUps.getInstance().ulc.loginConfirm.setVisible(false);
		StorageAndSetUps.getInstance().ulc.loginExistingUser.setVisible(true);
		StorageAndSetUps.getInstance().ulc.createNewUser.setVisible(true);
		StorageAndSetUps.getInstance().ulc.goBack.setVisible(false);
		StorageAndSetUps.getInstance().ulc.quitButton.setVisible(true);
	}
	
	
	// Event Listener on Button[#quitButton].onAction
	@FXML
	public void quitPress(ActionEvent event) throws IOException{
		FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("QuitPage.fxml"));
        Parent root1 = (Parent) fxmlLoader.load();
        Stage stage = new Stage();
        stage.initModality(Modality.APPLICATION_MODAL);
        Scene scene = new Scene(root1);
        stage.setTitle("Quit Page");
        stage.setScene(scene);
        stage.setResizable(false);
        stage.initStyle(StageStyle.UNDECORATED);
        stage.show();
	}
	// Event Listener on Button[#loginExistingUser].onAction
	@FXML
	public void loginExistingUserPress(ActionEvent event) throws IOException {
		StorageAndSetUps.getInstance().ulc.passwordInput.setVisible(true);
		StorageAndSetUps.getInstance().ulc.userList.setVisible(true);
		StorageAndSetUps.getInstance().ulc.loginConfirm.setVisible(true);
		StorageAndSetUps.getInstance().ulc.loginExistingUser.setVisible(false);
		StorageAndSetUps.getInstance().ulc.createNewUser.setVisible(false);
		StorageAndSetUps.getInstance().ulc.quitButton.setVisible(false);
		StorageAndSetUps.getInstance().ulc.goBack.setVisible(true);
		
	}
	// Event Listener on Button[#createNewUser].onAction
	@FXML
	public void createNewUserPress(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#loginConfirm].onAction
	@FXML
	public void loginConfirmPress(ActionEvent event) {
		// TODO Autogenerated
	}
}
